[package]
name = "tptp-graph"
version = "0.1.0"
authors = ["Michael Rawson <michael@rawsons.uk>"]
edition = "2018"

[lib]
name = "tptp_graph"
crate-type = ["cdylib"]

[dependencies]
fnv = "1.0"
numpy = "0.14"
tptp = "0.29"

[dependencies.pyo3]
version = "0.14"
features = ["extension-module"]
