[package]
name = "tptp-graph"
version = "0.1.0"
authors = ["Michael Rawson <michael@rawsons.uk>"]
edition = "2018"

[dependencies]
glob = "0.3"
petgraph = "0.5"
tptp = "0.14"

[profile.release]
codegen-units = 1
lto = true
